openapi: "3.0.0"
info:
  version: 1.0.0
  title: VA My Health APIs
  license:
    name: CC0 1.0 Universal
  description: >
    The Department of Veterans Affairs My Health APIs. All paths are relative to https://api.va.gov/my_health.
servers:
  - url: https://api.va.gov/my_health
paths:
  /v1/medical_records/allergies:
    get:
      description: List patient allergies
      operationId: list_allergies
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                description: >
                  FHIR Bundle containing AllergyIntolerance objects. The schema can be found at
                  <a href='https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.allergyIntolerance.html'>Allergies</a>.
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Forbidden
      summary: /v1/medical_records/allergies
  /v1/medical_records/allergies/{id}:
    get:
      description: Get a patient allergy
      operationId: get_allergy
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                description: >
                  FHIR AllergyIntolerance. The schema can be found at
                  <a href='https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.allergyIntolerance.html'>Allergies</a>.
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Forbidden
      summary: /v1/medical_records/allergies/{id}
  /v1/medical_records/clinical_notes:
    get:
      description: List patient clinical notes
      operationId: list_clinical_notes
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                description: >
                  FHIR Bundle containing DocumentReference objects. The schema can be found at
                  <a href='https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.note.html'>Care Summaries and Notes</a>.
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Forbidden
      summary: /v1/medical_records/clinical_notes
  /v1/medical_records/clinical_notes/{id}:
    get:
      description: Get a clinical note
      operationId: get_clinical_note
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                description: >
                  FHIR DocumentReference. The schema can be found at
                  <a href='https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.note.html'>Care Summaries and Notes</a>.
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Forbidden
      summary: /v1/medical_records/clinical_notes/{id}
  /v1/medical_records/conditions:
    get:
      description: List patient health conditions
      operationId: list_conditions
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                description: >
                  FHIR Bundle containing Condition objects. The schema can be found at
                  <a href='https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.condition.html'>Health Conditions</a>.
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Forbidden
      summary: /v1/medical_records/conditions
  /v1/medical_records/conditions/{id}:
    get:
      description: Get a patient health condition
      operationId: get_condition
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                description: >
                  FHIR Condition. The schema can be found at
                  <a href='https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.condition.html'>Health Conditions</a>.
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Forbidden
      summary: /v1/medical_records/conditions/{id}
  /v1/medical_records/labs_and_tests:
    get:
      description: >
        List patient labs and tests. This API call runs three separate backend calls, then merges the results. It
        returns results for the Chemistry/Hematology, EKG, Microbiology, Pathology, and Radiology domains.
      operationId: list_labs_and_tests
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                description: >
                  FHIR Bundle containing DiagnosticReport and DocumentReference objects. The schemas can be found at
                  <a href='https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.chReport.html'>Chemistry/Hematology</a>,
                  <a href='https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.ecg.html'>EKG</a>,
                  <a href='https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.labReport.html'>Microbiology and Pathology</a>,
                  <a href='https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.imaging.html'>Radiology</a>
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Forbidden
      summary: /v1/medical_records/labs_and_tests
  /v1/medical_records/labs_and_tests/diagrep/{id}:
    get:
      description: |
        Get a patient labs and tests record of type DiagnosticReport. This is for Chemistry/Hematology,
        Microbiology, and Pathology results.
      operationId: get_labs_and_tests_diagrep
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                description: >
                  FHIR DiagnosticReport. The schemas can be found at
                  <a href='https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.chReport.html'>Chemistry/Hematology</a>,
                  <a href='https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.labReport.html'>Microbiology and Pathology</a>
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Forbidden
      summary: /v1/medical_records/labs_and_tests/diagrep/{id}
  /v1/medical_records/labs_and_tests/docref/{id}:
    get:
      description: |
        Get a patient labs and tests record of type DocumentReference. This is for EKG and Radiolody results.
      operationId: get_labs_and_tests_docref
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                description: >
                  FHIR DocumentReference. The schema can be found at
                  <a href='https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.ecg.html'>EKG</a>,
                  <a href='https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.imaging.html'>Radiology</a>
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Forbidden
      summary: /v1/medical_records/labs_and_tests/docref/{id}
  /v1/medical_records/vaccines:
    get:
      description: List patient vaccines
      operationId: list_vaccines
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                description: >
                  FHIR Bundle containing Immunization objects. The schema can be found at
                  <a href='https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.immunization.html'>Immunization</a>
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Forbidden
      summary: /v1/medical_records/vaccines
  /v1/medical_records/vaccines/{id}:
    get:
      description: Get a patient vaccine
      operationId: get_vaccine
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                description: >
                  FHIR Immunization. The schema can be found at
                  <a href='https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.immunization.html'>Immunization</a>
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Forbidden
      summary: /v1/medical_records/vaccines/{id}
  /v1/medical_records/vitals:
    get:
      description: List patient vital records
      operationId: list_vitals
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                description: >
                  FHIR Bundle containing Observation objects. The schema can be found at
                  <a href='https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.vitals.html'>Vitals</a>
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Forbidden
      summary: /v1/medical_records/vitals
  /v1/medical_records/vitals/{id}:
    get:
      description: Get a patient vital record
      operationId: get_vaccine
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                description: >
                  FHIR Observation. The schema can be found at
                  <a href='https://department-of-veterans-affairs.github.io/mhv-fhir-phr-mapping/StructureDefinition-VA.MHV.PHR.vitals.html'>Vitals</a>
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Forbidden
      summary: /v1/medical_records/vitals/{id}

  /v1/messaging/folders:
    get:
      description: List available secure messaging folders
      operationId: get_folders
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: ./schemas/SecureMessagingFolders.yml
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/folders
      parameters:
        - $ref: "#/components/parameters/InflectionHeader"
        - name: requires_oh_messages
          in: query
          description: Count of folder messages includes Oracle Health messages if set to "1"
          required: false
          schema:
            type: string
            enum:
              - "0"
              - "1"
  /v1/messaging/folders/{id}:
    get:
      description: Get a secure messaging folder
      operationId: get_folder
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: ./schemas/SecureMessagingFolder.yml
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/folders/{id}
      parameters:
        - $ref: "#/components/parameters/InflectionHeader"
        - name: requires_oh_messages
          in: query
          description: Count of folder messages includes Oracle Health messages if set to "1"
          required: false
          schema:
            type: string
            enum:
              - "0"
              - "1"
    put:
      description: Rename an existing folder
      operationId: post_rename_folder
      requestBody:
        content:
          application/json:
            schema:
              example:
                name: New Name for Folder
              type: object
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: ./schemas/SecureMessagingFolder.yml
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/folders/{id}
  /v1/messaging/folders/{id}/messages:
    get:
      description: |
        List messages in a secure messaging folder.

        When listing messages, the response for each message will include most but not all of the message attributes.
        Specifically, the message body and attachment information is not included. Those attributes can be obtained by
        getting the specific message resource.
      operationId: get_folder_messages
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: ./schemas/SecureMessageList.yml
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/folders/{id}/messages
      parameters:
        - $ref: "#/components/parameters/InflectionHeader"
  /v1/messaging/folders/{id}/threads:
    get:
      description: List threads in a secure messaging folder.
      operationId: get_folder_threads
      parameters:
        - description: The id of the folder that threads are being retrieved from
          in: path
          name: folderId
          required: true
          schema:
            type: string
        - description: The size of the pagination you want
          in: query
          name: pageSize,
          required: true
          schema:
            type: string
        - description: The page number to get based on your page size
          in: query
          name: pageNumber,
          required: true
          schema:
            type: string
        - description: The field to sort the results by
          in: query
          name: sortField,
          required: true
          schema:
            type: string
            enum: [SENDER_NAME, RECIPIENT_NAME, SENT_DATE, DRAFT_DATE]
        - description: The order to sort the results by
          in: query
          name: sortOrder,
          required: true
          schema:
            type: string
            enum: [ASC, DESC]
        - name: requires_oh_messages
          in: query
          description: Includes Oracle Health threads if set to "1"
          required: false
          schema:
            type: string
            enum:
              - "0"
              - "1"
        - $ref: "#/components/parameters/InflectionHeader"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: ./schemas/SecureMessageThreadList.yml
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/folders/{id}/threads
  /v1/messaging/folders/{id}/search:
    post:
      description: |
        Search messages in a secure messaging folder. If multiple search criteria are specified, each returned search
        result will match ALL criteria. Pagination is supported and is handled by the upstream MHV server.

        When listing messages, the response for each message will include most but not all of the message attributes.
        Specifically, the message body and attachment information is not included. Those attributes can be obtained by
        getting the specific message resource.
      operationId: search_folder
      parameters:
        - description: The page of results to be returned (passed through to MHV API)
          in: query
          name: page
          required: false
          schema:
            type: integer
            default: 1
        - description: The number of results per page (passed through to MHV API)
          in: query
          name: per_page,
          required: false
          schema:
            type: integer
            default: 250
        - name: requires_oh_messages
          in: query
          description: Includes Oracle Health messages in search results if set to "1"
          required: false
          schema:
            type: string
            enum:
              - "0"
              - "1"
        - $ref: "#/components/parameters/InflectionHeader"
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas/SecureMessageSearchRequest.yml
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: ./schemas/SecureMessageSearch.yml
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/folders/{id}/search
  /v1/messaging/message_drafts:
    post:
      description: Save a new draft message
      operationId: post_create_message_draft
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas/SecureMessageNewMessageRequest.yml
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: ./schemas/SecureMessageNewMessageRequest.yml
          description: Created
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/message_drafts
      parameters:
        - $ref: "#/components/parameters/InflectionHeader"
  /v1/messaging/message_drafts/{id}:
    put:
      description: Update an existing draft message
      operationId: post_create_message_draft
      parameters:
        - description: The id of the draft that is to be updated
          in: path
          name: id
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/InflectionHeader"
      requestBody:
        content:
          application/json:
            schema:
              example:
                body: the updated message
              type: object
        required: true
      responses:
        "204":
          description: No Content
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/message_drafts/{id}
  /v1/messaging/message_drafts/{reply_id}/replydraft:
    post:
      description: Save a new draft message as a reply to an existing message
      operationId: post_create_message_draft_reply
      parameters:
        - description: The id of the message that will be replied to
          in: path
          name: reply_id
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/InflectionHeader"
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas/SecureMessageNewMessageRequest.yml
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: ./schemas/SecureMessageNewMessageRequest.yml
          description: Created
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/message_drafts/{reply_id}/replydraft
  /v1/messaging/message_drafts/{reply_id}/replydraft/{draft_id}:
    post:
      description: Edit a draft message that was a reply to an existing message
      operationId: post_create_message_draft_reply
      parameters:
        - description: The id of the message that will be replied to
          in: path
          name: reply_id
          required: true
          schema:
            type: string
        - description: The id of the draft that is to be updated
          in: path
          name: draft_id
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/InflectionHeader"
      requestBody:
        content:
          application/json:
            schema:
              example:
                body: the updated message
              type: object
        required: true
      responses:
        "204":
          description: No Content
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/message_drafts/{reply_id}/replydraft/{draft_id}
  /v1/messaging/messages:
    post:
      description: Send a new secure message
      operationId: post_create_message
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas/SecureMessageNewMessageRequest.yml
          multipart/form-data:
            schema:
              properties:
                message:
                  description:
                    Stringified JSON with same parameters as if this was
                    an application/json request (e.g. '{"category":"OTHER","recipient_id":1763526,"body":"test
                    message"}')
                  type: string
                uploads[]:
                  description: |
                    One or more message attachments.

                    <strong>NOTES:</strong>
                    <ul>
                    <li>A single message may have a maximum of 4 attachments.</li>
                    <li>A single attachment cannot exceed 3 MB</li>
                    <li>All attachments combined cannot exceed 6 MB</li>
                    <li>Supported file types/extensions: doc, docx, gif, jpg, pdf, png, rtf, txt, xls, xlsx.</li>
                    </ul>
                  items:
                    format: binary
                    type: string
                  type: array
              type: object
        description: |
          New message body.

          <strong>NOTES:</strong>
          <ul>
            <li>If a subject isn't included, default subject will be "{{Category}} Inquiry" (e.g. Medication Inquiry)</li>
            <li>Messages can only be replied to for 120 days.  After that, the message is considered "expired"</li>
            <li>If sending a draft, include the draft's ID in the request body as `draft_id`. Draft will be deleted once sent. Any fields included in request body will overwrite original draft contents.
            <li>If including file attachments, this request must be sent as <i>multipart/form-data</i></li>
            <li>
              File attachment restrictions (as imposed by MHV):
              <ul>
                <li>User may attach up to 4 files</li>
                <li>Accepted formats: doc, docx, jpg, pdf, png, rtf, txt, xls, xlsx</li>
                <li>Single attachment cannot exceed 3 MB</li>
                <li>Total attachment cannot exceed 6 MB</li>
              </ul>
            </li>
          </ul>
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: ./schemas/SecureMessageDetail.yml
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/messages
      parameters:
        - $ref: "#/components/parameters/InflectionHeader"
  /v1/messaging/messages/categories:
    get:
      description: List available message categories
      operationId: get_categories
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: ./schemas/SecureMessageCategories.yml
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/messages/categories
      parameters:
        - $ref: "#/components/parameters/InflectionHeader"
  /v1/messaging/messages/signature:
    get:
      description: Gets user message signature preferences
      operationId: get_signature
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: ./schemas/SecureMessageSignature.yml
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/messages/signature
      parameters:
        - $ref: "#/components/parameters/InflectionHeader"
  /v1/messaging/messages/{id}:
    delete:
      description: Moves a secure message to the "Deleted" folder
      operationId: delete_message
      parameters:
        - description: The id of the message that is to be deleted
          in: path
          name: id
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/InflectionHeader"
      responses:
        "204":
          description: The message was deleted successfully
        "400":
          content:
            application/json:
              example:
                errors:
                  - code: SM114
                    detail: Unable to move message
                    status: "400"
                    title: Operation failed
              schema:
                $ref: ./schemas/Errors.yml
          description: Bad Request
        "401":
          content:
            application/json:
              example:
                errors:
                  - code: "401"
                    detail: IAM user session is inactive
                    status: "401"
                    title: Not authorized
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              example:
                errors:
                  - code: "403"
                    detail: You do not have access to messaging
                    status: "403"
                    title: Forbidden
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/messages/{id}
    get:
      description: |
        Get a secure message <strong>and mark the message as read</strong>.

        <strong>NOTES:</strong>
        <ul>
          <li>Unlike listing messages in a folder, the message resource returned from this operation will include
        the message body and attachment information.</li>
          <li>This GET operation is not fully idempotent and will set readReceipt field as 'READ'</li>
          <li>If message has an attachment included, attachmentSize is displayed in bytes</li>
        </ul>
      operationId: get_message
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: ./schemas/SecureMessageDetail.yml
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/messages/{id}
      parameters:
        - $ref: "#/components/parameters/InflectionHeader"
    patch:
      description: Moves a secure message to a specified folder
      operationId: post_move_message
      parameters:
        - description: The id of the message that is to be moved
          in: path
          name: id
          required: true
          schema:
            type: string
        - description: The id of the folder that the message is to be moved to
          in: query
          name: folder_id,
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/InflectionHeader"
      responses:
        "204":
          description: The message was moved successfully
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/messages/{id}/move
  /v1/messaging/messages/{id}/attachments/{attachment_id}:
    get:
      description: |
        Get a secure message attachment content as a direct binary download. Secure messaging supports the following file types/extensions: doc, docx, gif, jpg, pdf, png, rtf, txt, xls, xlsx.
      operationId: get_attachment
      parameters:
        - description: ID of the message that we are retrieving attachments of
          in: path
          name: id
          required: true
          schema:
            type: integer
        - $ref: "#/components/parameters/InflectionHeader"
      responses:
        "200":
          content:
            application/octet-stream:
              schema:
                format: binary
                type: string
          description: OK
          headers:
            Content-Disposition:
              description: |
                This header will have the value of "attachment", and a "filename" parameter containing the original filename of the attached content.
              schema:
                type: string
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/messages/{id}/attachments/{attachment_id}
  /v1/messaging/messages/{id}/reply:
    post:
      description: |
        Send reply to a secure message

        <strong>NOTE:</strong> If including file attachments, this request must be sent as <i>multipart/form-data</i>

        File attachment restrictions (as imposed by MHV):
        <ul>
          <li>User may attach up to 4 files</li>
          <li>Accepted formats: doc, docx, jpg, pdf, png, rtf, txt, xls, xlsx</li>
          <li>Single attachment cannot exceed 3 MB</li>
          <li>Total attachment cannot exceed 6 MB</li>
        </ul>
      operationId: post_create_message_reply
      parameters:
        - description: ID of the message that is being replied to
          in: path
          name: id
          required: true
          schema:
            type: integer
        - $ref: "#/components/parameters/InflectionHeader"
      requestBody:
        content:
          application/json:
            schema:
              $ref: ./schemas/SecureMessageReplyRequest.yml
          multipart/form-data:
            schema:
              properties:
                message:
                  description:
                    Stringified JSON with same parameters as if this was
                    an application/json request (e.g. '{"body":"test body with attachment"}')
                  type: string
                uploads[]:
                  description: |
                    One or more message attachments.

                    <strong>NOTES:</strong>
                    <ul>
                    <li>A single message may have a maximum of 4 attachments.</li>
                    <li>A single attachment cannot exceed 3 MB</li>
                    <li>All attachments combined cannot exceed 6 MB</li>
                    <li>Supported file types/extensions: doc, docx, gif, jpg, pdf, png, rtf, txt, xls, xlsx.</li>
                    </ul>
                  items:
                    format: binary
                    type: string
                  type: array
              type: object
        description: Reply message body
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: ./schemas/SecureMessageDetail.yml
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/messages/{id}/reply
  /v1/messaging/messages/{id}/thread:
    get:
      description: |
        Gets a list of message summaries that are related to the message of the passed id.
      operationId: get_messages_for_thread
      responses:
        "200":
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: ./schemas/SecureMessageListInThread.yml
                  - $ref: ./schemas/SecureMessageListInThreadWithFullBody.yml
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/messages/{id}/thread
      parameters:
        - name: full_body
          in: query
          description: Include the full body of the messages and attachments meta in the response
          required: false
          schema:
            type: boolean
        - name: requires_oh_messages
          in: query
          description: Includes Oracle Health messages if set to "1"
          required: false
          schema:
            type: string
            enum:
              - "0"
              - "1"
        - $ref: "#/components/parameters/InflectionHeader"
  /v1/messaging/recipients:
    get:
      description: List available recipients to which messages may be sent
      operationId: get_triage_teams
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: ./schemas/SecureMessagingRecipients.yml
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/recipients
      parameters:
        - $ref: "#/components/parameters/InflectionHeader"
  /v1/messaging/allrecipients:
    get:
      description: List available recipients to which messages may be sent with advanced attributes
      operationId: get_all_triage_teams
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: ./schemas/SecureMessagingAllRecipients.yml
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/allrecipients
      parameters:
        - $ref: "#/components/parameters/InflectionHeader"
  /v1/messaging/threads/{id}/move:
    patch:
      description:
        Moves all received messages in a secure message thread to a specified folder. Sent
        messages, draft messages, and deleted messages will not be moved.
      operationId: post_move_thread
      parameters:
        - description: The id of the thread that is to be moved
          in: path
          name: id
          required: true
          schema:
            type: string
        - description: The id of the folder that the message is to be moved to
          in: query
          name: folder_id,
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/InflectionHeader"
      responses:
        "204":
          description: The message thread was moved successfully
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/messaging/threads/{id}/move
  /v1/prescriptions:
    get:
      description: List medications.
      operationId: get_prescriptions
      parameters:
        - description: One refill status to filter on
          in: query
          name: refill_status
          required: false
          schema:
            type: string
        - description: The page number to get based on your page size
          in: query
          name: page
          required: false
          schema:
            type: string
        - description: The size of the pagination you want
          in: query
          name: per_page
          required: false
          schema:
            type: string
        - description: The attribute to sort on, negated for descending
          in: query
          name: sort
          required: false
          schema:
            type: string
        - $ref: "#/components/parameters/InflectionHeader"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: ./schemas/PrescriptionList.yml
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/prescriptions
  /v1/prescriptions/{id}:
    get:
      description: Get prescription.
      operationId: get_prescription
      parameters:
        - description: prescription id
          in: path
          name: id
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/InflectionHeader"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: ./schemas/Prescription.yml
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/prescriptions/{id}
  /v1/prescriptions/{id}/refill:
    patch:
      description: Refill the prescription
      operationId: patch_refill_prescription
      parameters:
        - description: The id of the prescription
          in: path
          name: id
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/InflectionHeader"
      responses:
        "204":
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/prescriptions/{id}/refill
  /v1/prescriptions/list_refillable_prescriptions:
    get:
      description: List refillable medications.
      operationId: get_list_refillable_prescriptions
      parameters:
        - $ref: "#/components/parameters/InflectionHeader"
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: ./schemas/PrescriptionList.yml
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/prescriptions/list_refillable_prescriptions
  /v1/prescriptions/refill_prescriptions:
    patch:
      description: Refill the prescriptions
      operationId: patch_refill_prescription
      parameters:
        - description: Array of the prescription ids
          in: query
          name: ids
          required: true
          schema:
            type: array
            items:
              type: string

        - $ref: "#/components/parameters/InflectionHeader"
      responses:
        "204":
          description: Success
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/prescriptions/refill_prescriptions
  /v1/prescriptions/get_prescription_image/{cmopNdcNumber}:
    get:
      description: Get prescription image.
      operationId: get_prescription_image
      parameters:
        - description: cmopNdcNumber
          in: path
          name: cmopNdcNumber
          required: true
          schema:
            type: string
        - $ref: "#/components/parameters/InflectionHeader"
      responses:
        "200":
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    description: base64-encoded file contents
                    type: string
                    format: byte
          description: OK
        "401":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Unauthorized
        "403":
          content:
            application/json:
              schema:
                $ref: ./schemas/Errors.yml
          description: Not authorized for access to secure messages
      summary: /v1/prescriptions/list_refillable_prescriptions

components:
  securitySchemes:
    CookieAuth:
      type: apiKey
      name: api_session
      in: cookie
      description: An authenticated session is established using the Sessions Controller to initiate federated authentication with an external credential provider, after which an API session token is established in the api_session cookie.
  parameters:
    InflectionHeader:
      in: header
      name: X-Key-Inflection
      required: false
      schema:
        type: string
        enum: [camel, snake]
      description: Instructs the API to return camelCase keys rather than snake_case
    RequiresOHMessages:
      name: requires_oh_messages
      in: query
      required: false
      schema:
        type: string
        enum:
          - "0"
          - "1"
security:
  - CookieAuth: []
