{
  "openapi": "3.0.1",
  "info": {
    "title": "Benefits Claims",
    "version": "v2",
    "description": "## Background\n\nThe Benefits Claims API Version 2 offers internal consumers the ability to retrieve existing claim information, including status, by claim ID. Additional functionality will be added over time. \n\nYou should use the [Benefits Claims API Version 1](https://developer.va.gov/explore/benefits/docs/claims?version=current) if: \n\n-   You are not an internal consumer, and/or\n-   You want automatic establishment of disability compensation claims in Veterans Benefits Management System (VBMS) or power of attorney (POA)\n    \n## Technical Overview\n\nThis API accepts a payload of requests and responses with the payload identifying the claim and Veteran. Responses provide the submission’s processing status. Responses also provide a unique ID which can be used with the appropriate GET endpoint to return detailed, end-to-end claims status tracking. \n\nEnd-to-end claims tracking provides the status of claims as they move through the submission process, but does not return whether the claim was approved or denied. \n\n### Claim statuses\n\nWhen the claim is successfully submitted to Lighthouse, the status is Pending. Other statuses this API returns align with the [VA.gov claim status descriptions](https://www.va.gov/resources/what-your-claim-status-means/), which are: \n\n-   Claim received\n-   Initial review\n-   Evidence gathering, review, and decision\n-   Preparation for notification\n-   Complete\n\n### Finding a Veteran's unique VA ID\n\nThis API uses a unique Veteran identifier to identify the subject of each API request. This Veteran identifier can be retrieved by passing the Veteran’s first name, last name, DOB, and SSN to the ‘/veteran-id’ endpoint. This identifier should then be used as the Veteran ID parameter in request URLs.\n\nNote: though Veteran identifiers are typically static, they may change over time. If a specific Veteran ID suddenly responds with a ‘404 not found’ error, the identifier may have changed. It’s a good idea to periodically check the identifier for each Veteran.\n\n### Authentication and authorization\n\nTo make an API request, use our [client credentials grant](https://developer.va.gov/explore/authorization/docs/client-credentials?api=claims) to receive an [OAuth token](https://oauth.net/2/). \n\n### Test data for sandbox environment use\n\nWe use mock [test data in the sandbox environment](https://github.com/department-of-veterans-affairs/vets-api-clients/blob/master/test_accounts.md). Sandbox test data and test users for the Benefits Claims API are valid for all versions of the API.\n"
  },
  "tags": [
    {
      "name": "Veteran Identifier",
      "description": "Allows authenticated veterans and veteran representatives to retrieve a veteran's id."
    },
    {
      "name": "Claims",
      "description": "Allows authenticated and authorized users to access claims data for a given Veteran. No data is returned if the user is not authenticated and authorized.\n"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearer_token": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      },
      "productionOauth": {
        "type": "oauth2",
        "description": "This API uses OAuth 2 with the authorization code grant flow. [More info](https://developer.va.gov/explore/authorization?api=claims)",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://api.va.gov/oauth2/authorization",
            "tokenUrl": "https://api.va.gov/oauth2/token",
            "scopes": {
              "claim.read": "Retrieve claim data",
              "claim.write": "Submit claim data"
            }
          }
        }
      },
      "sandboxOauth": {
        "type": "oauth2",
        "description": "This API uses OAuth 2 with the authorization code grant flow. [More info](https://developer.va.gov/explore/authorization?api=claims)",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://sandbox-api.va.gov/oauth2/authorization",
            "tokenUrl": "https://sandbox-api.va.gov/oauth2/token",
            "scopes": {
              "claim.read": "Retrieve claim data",
              "claim.write": "Submit claim data"
            }
          }
        }
      }
    }
  },
  "paths": {
    "/veteran-id:find": {
      "post": {
        "summary": "Retrieve Veteran ID.",
        "tags": [
          "Veteran Identifier"
        ],
        "operationId": "postVeteranId",
        "security": [
          {
            "productionOauth": [
              "claim.read"
            ]
          },
          {
            "sandboxOauth": [
              "claim.read"
            ]
          },
          {
            "bearer_token": [

            ]
          }
        ],
        "description": "Allows authenticated and authorized users to retrieve a Veteran's ID.",
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "Veteran's unique identifier",
            "content": {
              "application/json": {
                "example": {
                  "id": "1012667145V762142"
                },
                "schema": {
                  "additionalProperties": false,
                  "properties": {
                    "id": {
                      "type": "string",
                      "example": "1012667145V762142"
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "example": {
                  "errors": [
                    {
                      "title": "invalid value for SSN",
                      "detail": "blank is not valid for SSN"
                    }
                  ]
                },
                "schema": {
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "additionalProperties": false,
                        "required": [
                          "title",
                          "detail"
                        ],
                        "properties": {
                          "title": {
                            "type": "string",
                            "description": "HTTP error title"
                          },
                          "detail": {
                            "type": "string",
                            "description": "HTTP error detail"
                          },
                          "source": {
                            "type": "object",
                            "additionalProperties": false,
                            "description": "Source of error",
                            "properties": {
                              "pointer": {
                                "type": "string",
                                "description": "Pointer to source of error"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "example": {
                  "errors": [
                    {
                      "title": "Not authorized",
                      "detail": "Not authorized"
                    }
                  ]
                },
                "schema": {
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "additionalProperties": false,
                        "required": [
                          "title",
                          "detail"
                        ],
                        "properties": {
                          "title": {
                            "type": "string",
                            "description": "HTTP error title"
                          },
                          "detail": {
                            "type": "string",
                            "description": "HTTP error detail"
                          },
                          "source": {
                            "type": "object",
                            "additionalProperties": false,
                            "description": "Source of error",
                            "properties": {
                              "pointer": {
                                "type": "string",
                                "description": "Pointer to source of error"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "errors": [
                    {
                      "title": "Forbidden",
                      "detail": "Forbidden"
                    }
                  ]
                },
                "schema": {
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "additionalProperties": false,
                        "required": [
                          "title",
                          "detail"
                        ],
                        "properties": {
                          "title": {
                            "type": "string",
                            "description": "HTTP error title"
                          },
                          "detail": {
                            "type": "string",
                            "description": "HTTP error detail"
                          },
                          "source": {
                            "type": "object",
                            "additionalProperties": false,
                            "description": "Source of error",
                            "properties": {
                              "pointer": {
                                "type": "string",
                                "description": "Pointer to source of error"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "example": {
                  "errors": [
                    {
                      "title": "Resource not found",
                      "detail": "Resource not found"
                    }
                  ]
                },
                "schema": {
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "additionalProperties": false,
                        "required": [
                          "title",
                          "detail"
                        ],
                        "properties": {
                          "title": {
                            "type": "string",
                            "description": "HTTP error title"
                          },
                          "detail": {
                            "type": "string",
                            "description": "HTTP error detail"
                          },
                          "source": {
                            "type": "object",
                            "additionalProperties": false,
                            "description": "Source of error",
                            "properties": {
                              "pointer": {
                                "type": "string",
                                "description": "Pointer to source of error"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "ssn",
                  "birthdate",
                  "firstName",
                  "lastName"
                ],
                "properties": {
                  "ssn": {
                    "type": "string",
                    "example": "796130115",
                    "description": "SSN of Veteran being represented"
                  },
                  "firstName": {
                    "type": "string",
                    "example": "Tamara",
                    "description": "First name of Veteran being represented"
                  },
                  "lastName": {
                    "type": "string",
                    "example": "Ellis",
                    "description": "Last name of Veteran being represented"
                  },
                  "birthdate": {
                    "type": "string",
                    "example": "1967-06-19",
                    "description": "Date of birth of Veteran being represented, in iso8601 format"
                  }
                },
                "example": {
                  "ssn": "796130115",
                  "firstName": "Tamara",
                  "lastName": "Ellis",
                  "birthdate": "1967-06-19"
                }
              }
            }
          },
          "required": true
        }
      }
    },
    "/veterans/{veteranId}/claims": {
      "get": {
        "summary": "Find all benefits claims for a Veteran.",
        "tags": [
          "Claims"
        ],
        "operationId": "findClaims",
        "security": [
          {
            "productionOauth": [
              "claim.read"
            ]
          },
          {
            "sandboxOauth": [
              "claim.read"
            ]
          },
          {
            "bearer_token": [

            ]
          }
        ],
        "description": "Retrieves all claims for Veteran.",
        "parameters": [
          {
            "name": "veteranId",
            "in": "path",
            "required": true,
            "example": "1012667145V762142",
            "description": "ID of Veteran",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "claim response",
            "content": {
              "application/json": {
                "example": [
                  {
                    "5103WaiverSubmitted": false,
                    "claimId": "555555555",
                    "claimType": "Compensation",
                    "dateFiled": "05/02/17",
                    "decisionLetterSent": false,
                    "developmentLetterSent": false,
                    "documentsNeeded": false,
                    "lighthouseId": null,
                    "status": "Complete"
                  }
                ],
                "schema": {
                  "type": "array",
                  "items": {
                    "additionalProperties": false,
                    "description": "Claim details",
                    "properties": {
                      "claimId": {
                        "type": "string",
                        "nullable": true,
                        "description": "Claim ID in VBMS",
                        "example": "600131328"
                      },
                      "claimType": {
                        "type": "string",
                        "description": "Name of claim type",
                        "example": "Appeals control"
                      },
                      "dateFiled": {
                        "type": "string",
                        "format": "date",
                        "description": "Date in YYYY-MM-DD the claim was first filed",
                        "example": "2018-06-04"
                      },
                      "documentsNeeded": {
                        "type": "boolean",
                        "description": "If true, the claim requires additional documents to be submitted",
                        "example": "false"
                      },
                      "developmentLetterSent": {
                        "type": "boolean",
                        "description": "If true, a development letter has been sent to the claimant regarding a benefit claim",
                        "example": "false"
                      },
                      "decisionLetterSent": {
                        "type": "boolean",
                        "description": "If true, a decision letter has been sent to the claimant regarding a benefit claim",
                        "example": "false"
                      },
                      "lighthouseId": {
                        "type": "string",
                        "nullable": true,
                        "description": "Claim ID in Lighthouse",
                        "example": "600131328"
                      },
                      "status": {
                        "type": "string",
                        "description": "Status of claim",
                        "example": "Complete"
                      },
                      "5103WaiverSubmitted": {
                        "type": "boolean",
                        "nullable": true,
                        "description": "If true, indicates a decision has been requested and/or a Waiver 5103 has been submitted",
                        "example": "false"
                      }
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "example": {
                  "errors": [
                    {
                      "title": "Not authorized",
                      "detail": "Not authorized"
                    }
                  ]
                },
                "schema": {
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "additionalProperties": false,
                        "required": [
                          "title",
                          "detail"
                        ],
                        "properties": {
                          "title": {
                            "type": "string",
                            "description": "HTTP error title"
                          },
                          "detail": {
                            "type": "string",
                            "description": "HTTP error detail"
                          },
                          "source": {
                            "type": "object",
                            "additionalProperties": false,
                            "description": "Source of error",
                            "properties": {
                              "pointer": {
                                "type": "string",
                                "description": "Pointer to source of error"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "errors": [
                    {
                      "title": "Forbidden",
                      "detail": "Forbidden"
                    }
                  ]
                },
                "schema": {
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "additionalProperties": false,
                        "required": [
                          "title",
                          "detail"
                        ],
                        "properties": {
                          "title": {
                            "type": "string",
                            "description": "HTTP error title"
                          },
                          "detail": {
                            "type": "string",
                            "description": "HTTP error detail"
                          },
                          "source": {
                            "type": "object",
                            "additionalProperties": false,
                            "description": "Source of error",
                            "properties": {
                              "pointer": {
                                "type": "string",
                                "description": "Pointer to source of error"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/veterans/{veteranId}/claims/{id}": {
      "get": {
        "summary": "Find claim by ID",
        "tags": [
          "Claims"
        ],
        "operationId": "findClaimById",
        "security": [
          {
            "productionOauth": [
              "claim.read"
            ]
          },
          {
            "sandboxOauth": [
              "claim.read"
            ]
          },
          {
            "bearer_token": [

            ]
          }
        ],
        "description": "Retrieves a specific claim for a Veteran",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "example": "1234",
            "description": "The ID of the claim being requested",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "veteranId",
            "in": "path",
            "required": true,
            "example": "1012667145V762142",
            "description": "ID of Veteran",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "claim response",
            "content": {
              "application/json": {
                "example": {
                  "5103WaiverSubmitted": false,
                  "benefitClaimTypeCode": "400PREDSCHRG",
                  "claimId": "555555555",
                  "claimType": "Compensation",
                  "contentionList": [
                    "abnormal heart (New)",
                    " abscess kidney (New)",
                    " encephalitis lethargica residuals (New)",
                    " dracunculiasis (New)",
                    " gingivitis (New)",
                    " abnormal weight loss (New)",
                    " groin condition (New)",
                    " metritis (New)"
                  ],
                  "dateFiled": "05/02/17",
                  "decisionLetterSent": false,
                  "developmentLetterSent": false,
                  "documentsNeeded": false,
                  "endProductCode": "404",
                  "lighthouseId": null,
                  "status": "Complete",
                  "submitterApplicationCode": "EBN",
                  "submitterRoleCode": "VET",
                  "supportingDocuments": [

                  ]
                },
                "schema": {
                  "type": "object",
                  "additionalProperties": false,
                  "properties": {
                    "claimId": {
                      "type": "string",
                      "nullable": true,
                      "description": "Claim ID in VBMS",
                      "example": "600131328"
                    },
                    "benefitClaimTypeCode": {
                      "type": "string",
                      "description": "Type Code of benefit claim",
                      "example": "400PREDSCHRG"
                    },
                    "claimType": {
                      "type": "string",
                      "description": "Name of claim type",
                      "example": "Appeals Control"
                    },
                    "contentionList": {
                      "type": "array",
                      "items": {
                        "type": "string"
                      },
                      "description": "The contentions being submitted with a claim",
                      "example": [
                        "abnormal heart (New)",
                        "abscess kidney (New)"
                      ]
                    },
                    "dateFiled": {
                      "type": "string",
                      "description": "The date a claim was filed",
                      "example": "5/17/20"
                    },
                    "decisionLetterSent": {
                      "type": "boolean",
                      "description": "If true, a decision letter has been sent to the claimant regarding a benefit claim"
                    },
                    "developmentLetterSent": {
                      "type": "boolean",
                      "description": "If true, a development letter has been sent to the claimant regarding a benefit claim"
                    },
                    "documentsNeeded": {
                      "type": "boolean",
                      "description": "If true, the claim requires additional documents to be submitted"
                    },
                    "endProductCode": {
                      "type": "string",
                      "description": "End product code of claim",
                      "example": "930"
                    },
                    "lighthouseId": {
                      "type": "string",
                      "nullable": true,
                      "description": "Claim ID in Lighthouse",
                      "example": "600131328"
                    },
                    "status": {
                      "type": "string",
                      "description": "Status of claim",
                      "example": "Complete"
                    },
                    "submitterApplicationCode": {
                      "type": "string",
                      "description": "Application Code of benefit claim submitter",
                      "example": "EBN"
                    },
                    "submitterRoleCode": {
                      "type": "string",
                      "description": "Role Code of benefit claim submitter",
                      "example": "VET"
                    },
                    "supportingDocuments": {
                      "type": "array",
                      "description": "Information regarding any supported documents attached to a claim",
                      "items": {
                        "properties": {
                          "id": {
                            "type": "string",
                            "description": "Unique identifier of document"
                          },
                          "md5": {
                            "type": "string",
                            "description": "Hashed representation of document"
                          },
                          "filename": {
                            "type": "string",
                            "description": "Name of document"
                          },
                          "uploadedAt": {
                            "type": "string",
                            "format": "date",
                            "description": "Date and time document was uploaded"
                          }
                        }
                      }
                    },
                    "5103WaiverSubmitted": {
                      "type": "boolean",
                      "nullable": true,
                      "description": "If true, indicates a decision has been requested and/or a Waiver 5103 has been submitted",
                      "example": "false"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "content": {
              "application/json": {
                "example": {
                  "errors": [
                    {
                      "title": "Not authorized",
                      "detail": "Not authorized"
                    }
                  ]
                },
                "schema": {
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "additionalProperties": false,
                        "required": [
                          "title",
                          "detail"
                        ],
                        "properties": {
                          "title": {
                            "type": "string",
                            "description": "HTTP error title"
                          },
                          "detail": {
                            "type": "string",
                            "description": "HTTP error detail"
                          },
                          "source": {
                            "type": "object",
                            "additionalProperties": false,
                            "description": "Source of error",
                            "properties": {
                              "pointer": {
                                "type": "string",
                                "description": "Pointer to source of error"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "content": {
              "application/json": {
                "example": {
                  "errors": [
                    {
                      "title": "Forbidden",
                      "detail": "Forbidden"
                    }
                  ]
                },
                "schema": {
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "additionalProperties": false,
                        "required": [
                          "title",
                          "detail"
                        ],
                        "properties": {
                          "title": {
                            "type": "string",
                            "description": "HTTP error title"
                          },
                          "detail": {
                            "type": "string",
                            "description": "HTTP error detail"
                          },
                          "source": {
                            "type": "object",
                            "additionalProperties": false,
                            "description": "Source of error",
                            "properties": {
                              "pointer": {
                                "type": "string",
                                "description": "Pointer to source of error"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Resource not found",
            "content": {
              "application/json": {
                "example": {
                  "errors": [
                    {
                      "title": "Resource not found",
                      "detail": "Claim not found"
                    }
                  ]
                },
                "schema": {
                  "required": [
                    "errors"
                  ],
                  "properties": {
                    "errors": {
                      "type": "array",
                      "items": {
                        "additionalProperties": false,
                        "required": [
                          "title",
                          "detail"
                        ],
                        "properties": {
                          "title": {
                            "type": "string",
                            "description": "HTTP error title"
                          },
                          "detail": {
                            "type": "string",
                            "description": "HTTP error detail"
                          },
                          "source": {
                            "type": "object",
                            "additionalProperties": false,
                            "description": "Source of error",
                            "properties": {
                              "pointer": {
                                "type": "string",
                                "description": "Pointer to source of error"
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "https://sandbox-api.va.gov/services/claims/{version}",
      "description": "VA.gov API sandbox environment",
      "variables": {
        "version": {
          "default": "v2"
        }
      }
    },
    {
      "url": "https://api.va.gov/services/claims/{version}",
      "description": "VA.gov API production environment",
      "variables": {
        "version": {
          "default": "v2"
        }
      }
    }
  ]
}
